spring:
  profiles:
    active: pro #运行环境
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # druid连接池的设置
    druid:
    # 初始化大小，最小，最大
      initial-size: 0
      minIdle: 5
      maxActive: 20
    # 配置获取连接等待超时的时间
      maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 30000
      validationQuery: select 1 from dual
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
  redis:
    timeout: 3000
    jedis:
      pool:
        max-wait: 200
        max-active: 200
        max-idle: 8
        min-idle: 0
  rabbitmq:
    publisher-confirms: true
server:
  tomcat:
    max-connections: 500
