spring:
  datasource:
    druid:
      username: mdf
      password: modefang
      url: jdbc:mysql://35.187.159.0:3306/demo?useUnicode=true&characterEncoding=utf-8&autoReconnect=true
  redis:
    password: modefang
    database: 0
    host: 35.187.159.0
    port: 6379
  rabbitmq:
    host: 35.187.159.0
    port: 5672
    virtual-host: /
    username: guest
    password: guest
server:
  port: 8080
